[project]
name = "netwatchscn"
version = "0.1.0"
description = "A command line tool that you can use to ping hosts, scan targets, sweep targets, and get banners + whois / dns data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "dnspython>=2.8.0",
    "flask>=3.1.3",
    "ipwhois>=1.3.0",
    "python-nmap>=0.7.1",
    "python-whois>=0.9.6",
    "rich>=14.3.3",
]

[project.scripts]
netwatchscn = "reconkit.main:main"
